var nombreData = [
    
    { name: "Ajaccio", nombre: "0" },
    { name: "Amiens", nombre: "7" },
    { name: "Angers", nombre: "21" },
    { name: "Bastia", nombre: "0" },
    { name: "Bordeaux", nombre: "19" },
    { name: "Brest", nombre: "4" },
    { name: "Caen", nombre: "14" },
    { name: "Dijon", nombre: "12" },
    { name: "Grenoble", nombre: "0" },
    { name: "Guingamp", nombre: "7" },
    { name: "Lens", nombre: "0" },
    { name: "Lille", nombre: "23" },
    { name: "Lorient", nombre: "0" },
    { name: "Lyon", nombre: "44" },
    { name: "Marseille", nombre: "14" },
    { name: "Metz", nombre: "10" },
    { name: "Monaco", nombre: "16" },
    { name: "Montpellier", nombre: "13" },
    { name: "Nancy", nombre: "0" },
    { name: "Nantes", nombre: "11" },
    { name: "Nice", nombre: "19" },
    { name: "Nîmes", nombre: "8" },
    { name: "Paris", nombre: "18" },
    { name: "Reims", nombre: "17" },
    { name: "Rennes", nombre: "5" },
    { name: "Saint-Étienne", nombre: "24" },
    { name: "Sochaux", nombre: "0" },
    { name: "Strasbourg", nombre: "16" },
    { name: "Toulouse", nombre: "13" },
    { name: "Troyes", nombre: "0" },
    { name: "Valenciennes", nombre: "0" },
    
    
]
